//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poland {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poland() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Poland", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ.
        /// </summary>
        internal static string AddYourCart {
            get {
                return ResourceManager.GetString("AddYourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng thành công, Chúng tôi sẽ liên lạc và gủi sản phẩm của bạn theo địa chỉ đã đăng ký!.
        /// </summary>
        internal static string AnnounceOrderSuccesful {
            get {
                return ResourceManager.GetString("AnnounceOrderSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải đăng ký thành viên của website!.
        /// </summary>
        internal static string AnnounceRegisterMember {
            get {
                return ResourceManager.GetString("AnnounceRegisterMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh nhật.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ thành công, chúng tôi sẽ hồi đáp bạn sau!.
        /// </summary>
        internal static string contactusSuccessfulwewillrespondtoyoulater {
            get {
                return ResourceManager.GetString("contactusSuccessfulwewillrespondtoyoulater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        internal static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tao.
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ của khách hàng.
        /// </summary>
        internal static string customerContact {
            get {
                return ResourceManager.GetString("customerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Tất cả.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được Phát Triển Bời.
        /// </summary>
        internal static string designedby {
            get {
                return ResourceManager.GetString("designedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi Tiết giỏ hàng.
        /// </summary>
        internal static string DetailCart {
            get {
                return ResourceManager.GetString("DetailCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng Email.
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư Điện Từ.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho phép.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string identify {
            get {
                return ResourceManager.GetString("identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập lúc.
        /// </summary>
        internal static string Loginat {
            get {
                return ResourceManager.GetString("Loginat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Tên.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Sản Phẩm.
        /// </summary>
        internal static string NameProduct {
            get {
                return ResourceManager.GetString("NameProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        internal static string newProduct {
            get {
                return ResourceManager.GetString("newProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm tương tự.
        /// </summary>
        internal static string otherPoduct {
            get {
                return ResourceManager.GetString("otherPoduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số DT.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá cả.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Tiết sản phẩm.
        /// </summary>
        internal static string productDetails {
            get {
                return ResourceManager.GetString("productDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Qualitity {
            get {
                return ResourceManager.GetString("Qualitity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Ký.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công!.
        /// </summary>
        internal static string RegisterSuccessful {
            get {
                return ResourceManager.GetString("RegisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký không thành công.
        /// </summary>
        internal static string RegisterUnsuccessful {
            get {
                return ResourceManager.GetString("RegisterUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        internal static string repassword {
            get {
                return ResourceManager.GetString("repassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn Ngữ:.
        /// </summary>
        internal static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server quá tải, vui lòng thử lại sau!.
        /// </summary>
        internal static string serveroverloadedpleasetryagainlater {
            get {
                return ResourceManager.GetString("serveroverloadedpleasetryagainlater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Tính.
        /// </summary>
        internal static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công.
        /// </summary>
        internal static string successfull {
            get {
                return ResourceManager.GetString("successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tiền.
        /// </summary>
        internal static string TotalMoney {
            get {
                return ResourceManager.GetString("TotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng sẩn phẩm.
        /// </summary>
        internal static string TotalProduction {
            get {
                return ResourceManager.GetString("TotalProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Dùng.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin Chào.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai Xác Nhận!.
        /// </summary>
        internal static string WrongCaptcha {
            get {
                return ResourceManager.GetString("WrongCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng của bạn.
        /// </summary>
        internal static string yourcart {
            get {
                return ResourceManager.GetString("yourcart", resourceCulture);
            }
        }
    }
}
